sitemap: https://tangx.in/sitemap.xml
# purge: true
push: true 
lastModInDays: 7

include:
  - https://tangx.in/css/style.css
  - https://tangx.in/index.xml
  - https://tangx.in/sitemap.xml

# exclude:
#   - posts
